(function() {
var k=void 0,l=!0,m=null,p=!1,q=this;function aa(){}function r(b){return b!==k}function u(b){return"string"==typeof b}function ba(b,a,c){return b.call.apply(b.bind,arguments)}function ca(b,a,c){if(!b)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return b.apply(a,c)}}return function(){return b.apply(a,arguments)}}
function v(b,a,c){v=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ba:ca;return v.apply(m,arguments)}var da=Date.now||function(){return+new Date};function w(b,a){function c(){}c.prototype=a.prototype;b.Ea=a.prototype;b.prototype=new c}Function.prototype.bind=Function.prototype.bind||function(b,a){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,b);return v.apply(m,c)}return v(this,b)};function ea(b,a){for(var c=1;c<arguments.length;c++){var d=String(arguments[c]).replace(/\$/g,"$$$$");b=b.replace(/\%s/,d)}return b}function fa(b){if(!ga.test(b))return b;-1!=b.indexOf("&")&&(b=b.replace(ha,"&amp;"));-1!=b.indexOf("<")&&(b=b.replace(ia,"&lt;"));-1!=b.indexOf(">")&&(b=b.replace(ja,"&gt;"));-1!=b.indexOf('"')&&(b=b.replace(ka,"&quot;"));return b}var ha=/&/g,ia=/</g,ja=/>/g,ka=/\"/g,ga=/[&<>\"]/;function x(b){Error.captureStackTrace?Error.captureStackTrace(this,x):this.stack=Error().stack||"";b&&(this.message=String(b))}w(x,Error);x.prototype.name="CustomError";function la(b,a){a.unshift(b);x.call(this,ea.apply(m,a));a.shift();this.va=b}w(la,x);la.prototype.name="AssertionError";function ma(b,a){throw new la("Failure"+(b?": "+b:""),Array.prototype.slice.call(arguments,1));};var z=Array.prototype,A=z.indexOf?function(b,a,c){return z.indexOf.call(b,a,c)}:function(b,a,c){c=c==m?0:0>c?Math.max(0,b.length+c):c;if(u(b))return!u(a)||1!=a.length?-1:b.indexOf(a,c);for(;c<b.length;c++)if(c in b&&b[c]===a)return c;return-1},na=z.filter?function(b,a,c){return z.filter.call(b,a,c)}:function(b,a,c){for(var d=b.length,e=[],f=0,g=u(b)?b.split(""):b,h=0;h<d;h++)if(h in g){var n=g[h];a.call(c,n,h,b)&&(e[f++]=n)}return e};
function oa(b,a,c){return 2>=arguments.length?z.slice.call(b,a):z.slice.call(b,a,c)};function B(b,a){this.x=r(b)?b:0;this.y=r(a)?a:0}B.prototype.toString=function(){return"("+this.x+", "+this.y+")"};B.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};var C,pa,D,ra;function sa(){return q.navigator?q.navigator.userAgent:m}ra=D=pa=C=p;var E;if(E=sa()){var ta=q.navigator;C=0==E.indexOf("Opera");pa=!C&&-1!=E.indexOf("MSIE");D=!C&&-1!=E.indexOf("WebKit");ra=!C&&!D&&"Gecko"==ta.product}var ua=C,F=pa,G=ra,va=D;function wa(){var b=q.document;return b?b.documentMode:k}var H;
a:{var I="",J;if(ua&&q.opera)var xa=q.opera.version,I="function"==typeof xa?xa():xa;else if(G?J=/rv\:([^\);]+)(\)|;)/:F?J=/MSIE\s+([^\);]+)(\)|;)/:va&&(J=/WebKit\/(\S+)/),J)var ya=J.exec(sa()),I=ya?ya[1]:"";if(F){var za=wa();if(za>parseFloat(I)){H=String(za);break a}}H=I}var Aa={};
function Ba(b){if(!Aa[b]){for(var a=0,c=String(H).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(c.length,d.length),f=0;0==a&&f<e;f++){var g=c[f]||"",h=d[f]||"",n=RegExp("(\\d*)(\\D*)","g"),y=RegExp("(\\d*)(\\D*)","g");do{var s=n.exec(g)||["","",""],t=y.exec(h)||["","",""];if(0==s[0].length&&0==t[0].length)break;a=((0==s[1].length?0:parseInt(s[1],10))<(0==t[1].length?0:parseInt(t[1],10))?-1:(0==s[1].length?0:parseInt(s[1],10))>
(0==t[1].length?0:parseInt(t[1],10))?1:0)||((0==s[2].length)<(0==t[2].length)?-1:(0==s[2].length)>(0==t[2].length)?1:0)||(s[2]<t[2]?-1:s[2]>t[2]?1:0)}while(0==a)}Aa[b]=0<=a}}var Ca=q.document,Da=!Ca||!F?k:wa()||("CSS1Compat"==Ca.compatMode?parseInt(H,10):5);function Ea(b){return Fa(b||arguments.callee.caller,[])}
function Fa(b,a){var c=[];if(0<=A(a,b))c.push("[...circular reference...]");else if(b&&50>a.length){c.push(Ga(b)+"(");for(var d=b.arguments,e=0;e<d.length;e++){0<e&&c.push(", ");var f;f=d[e];switch(typeof f){case "object":f=f?"object":"null";break;case "string":break;case "number":f=String(f);break;case "boolean":f=f?"true":"false";break;case "function":f=(f=Ga(f))?f:"[fn]";break;default:f=typeof f}40<f.length&&(f=f.substr(0,40)+"...");c.push(f)}a.push(b);c.push(")\n");try{c.push(Fa(b.caller,a))}catch(g){c.push("[exception trying to get caller]\n")}}else b?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function Ga(b){if(K[b])return K[b];b=String(b);if(!K[b]){var a=/function ([^\(]+)/.exec(b);K[b]=a?a[1]:"[Anonymous]"}return K[b]}var K={};function L(b,a,c,d,e){this.reset(b,a,c,d,e)}L.prototype.na=0;L.prototype.R=m;L.prototype.Q=m;var Ha=0;L.prototype.reset=function(b,a,c,d,e){this.na="number"==typeof e?e:Ha++;this.Fa=d||da();this.u=b;this.ga=a;this.ua=c;delete this.R;delete this.Q};L.prototype.W=function(b){this.u=b};function M(b){this.ha=b}M.prototype.B=m;M.prototype.u=m;M.prototype.H=m;M.prototype.c=m;function Ia(b,a){this.name=b;this.value=a}Ia.prototype.toString=function(){return this.name};var Ja=new Ia("WARNING",900),Ka=new Ia("CONFIG",700);M.prototype.getParent=function(){return this.B};M.prototype.W=function(b){this.u=b};function La(b){if(b.u)return b.u;if(b.B)return La(b.B);ma("Root logger has no level set.");return m}
M.prototype.log=function(b,a,c){if(b.value>=La(this).value){b=this.ca(b,a,c);a="log:"+b.ga;q.console&&(q.console.timeStamp?q.console.timeStamp(a):q.console.markTimeline&&q.console.markTimeline(a));q.msWriteProfilerMark&&q.msWriteProfilerMark(a);for(a=this;a;){c=a;var d=b;if(c.c)for(var e=0,f=k;f=c.c[e];e++)f(d);a=a.getParent()}}};
M.prototype.ca=function(b,a,c){var d=new L(b,String(a),this.ha);if(c){d.R=c;var e;var f=arguments.callee.caller;try{var g;var h;c:{for(var n=["window","location","href"],y=q,s;s=n.shift();)if(y[s]!=m)y=y[s];else{h=m;break c}h=y}if(u(c))g={message:c,name:"Unknown error",lineNumber:"Not available",fileName:h,stack:"Not available"};else{var t,qa,n=p;try{t=c.lineNumber||c.ta||"Not available"}catch(Lb){t="Not available",n=l}try{qa=c.fileName||c.filename||c.sourceURL||q.$googDebugFname||h}catch(Mb){qa=
"Not available",n=l}g=n||!c.lineNumber||!c.fileName||!c.stack?{message:c.message,name:c.name,lineNumber:t,fileName:qa,stack:c.stack||"Not available"}:c}e="Message: "+fa(g.message)+'\nUrl: <a href="view-source:'+g.fileName+'" target="_new">'+g.fileName+"</a>\nLine: "+g.lineNumber+"\n\nBrowser stack:\n"+fa(g.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+fa(Ea(f)+"-> ")}catch(pb){e="Exception trying to expose exception! You win, we lose. "+pb}d.Q=e}return d};var Ma={},N=m;
function Na(b){N||(N=new M(""),Ma[""]=N,N.W(Ka));var a;if(!(a=Ma[b])){a=new M(b);var c=b.lastIndexOf("."),d=b.substr(c+1),c=Na(b.substr(0,c));c.H||(c.H={});c.H[d]=a;a.B=c;Ma[b]=a}return a};if(G||F){var Oa;if(Oa=F)Oa=F&&9<=Da;Oa||G&&Ba("1.9.1")}F&&Ba("9");function Pa(b){b=b.className;return u(b)&&b.match(/\S+/g)||[]}function Qa(b,a){for(var c=Pa(b),d=oa(arguments,1),e=c,f=0;f<d.length;f++)0<=A(e,d[f])||e.push(d[f]);b.className=c.join(" ")}function Ra(b,a){var c=Pa(b),d=oa(arguments,1),c=Sa(c,d);b.className=c.join(" ")}function Sa(b,a){return na(b,function(b){return!(0<=A(a,b))})}function Ta(b){var a=Pa(b);!(0<=A(a,"selected"))?Qa(b,"selected"):Ra(b,"selected")};function O(b,a,c){var d=document;c=c||d;b=b&&"*"!=b?b.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(b||a))return c.querySelectorAll(b+(a?"."+a:""));if(a&&c.getElementsByClassName){c=c.getElementsByClassName(a);if(b){for(var d={},e=0,f=0,g;g=c[f];f++)b==g.nodeName&&(d[e++]=g);d.length=e;return d}return c}c=c.getElementsByTagName(b||"*");if(a){d={};for(f=e=0;g=c[f];f++)b=g.className,"function"==typeof b.split&&0<=A(b.split(/\s+/),a)&&(d[e++]=g);d.length=e;return d}return c};var Ua=0,Va=/Mac OS X.+Silk\//;function Wa(b,a,c,d){return b<<21|a<<14|c<<7|d}var Xa=/OS (\d)_(\d)(?:_(\d))?/;function Ya(b){window.addEventListener("resize",b,p)}function P(b,a,c,d,e){var f=!!d;b.addEventListener(a,c,f);e&&(P(b,"DOMFocusIn",function(d){d.target&&"TEXTAREA"==d.target.tagName&&b.removeEventListener(a,c,f)}),P(b,"DOMFocusOut",function(d){d.target&&"TEXTAREA"==d.target.tagName&&b.addEventListener(a,c,f)}))}
function Za(b,a,c,d){var e=document.createEvent("HTMLEvents");e.initEvent(a,l,l);e.sender=c;e.ba=d;b.dispatchEvent(e)}var Q=/iPhone|iPod|iPad/.test(navigator.userAgent)||-1!=navigator.userAgent.indexOf("Android")||Va.test(navigator.userAgent),R=window.navigator.msPointerEnabled,$a=Q?"touchstart":R?"MSPointerDown":"mousedown",ab=Q?"touchmove":R?"MSPointerMove":"mousemove",bb=Q?"touchend":R?"MSPointerUp":"mouseup",cb=R?"MSPointerCancel":"touchcancel";
function db(b){return function(a){a.touches=[];a.targetTouches=[];a.changedTouches=[];a.type!=bb&&(a.touches[0]=a,a.targetTouches[0]=a);a.changedTouches[0]=a;b(a)}}function S(b){return R?[b]:b.changedTouches}function T(b){return R?b.pointerId:b.identifier}var U,eb,fb,gb,hb=Na("wireless.events.clickbuster");
function ib(b){if(!(2500<da()-eb)){var a=new B(b.clientX,b.clientY);if(1>a.x&&1>a.y)hb.log(Ja,"Not busting click on label elem at ("+a.x+", "+a.y+")",k);else{for(var c=0;c<U.length;c+=2)if(25>Math.abs(a.x-U[c])&&25>Math.abs(a.y-U[c+1])){U.splice(c,c+2);return}hb.log(Ja,"busting click at "+a.x+", "+a.y,k);b.stopPropagation();b.preventDefault();(b=fb)&&b()}}}
function jb(b){var a=new B((b.touches||[b])[0].clientX,(b.touches||[b])[0].clientY);U.push(a.x,a.y);window.setTimeout(function(){for(var b=a.x,d=a.y,e=0;e<U.length;e+=2)if(U[e]==b&&U[e+1]==d){U.splice(e,e+2);break}fb=k},2500)}function kb(){this.h=[];this.f=[]}function lb(b,a){for(;b.length&&250<a-b[1]||10<b.length;)b.splice(0,2)}function mb(b,a){var c=Math.abs(a);5<c&&(c=6>b.f.length?1:5);return c*(0>a?-1:1)}
function V(b,a,c){this.d=b;this.i=a;this.l=c;this.j=[];this.p=[];this.D=[];this.F=[];this.s=[];this.t=[]}V.prototype.b=0;function nb(b,a){for(var c,d=S(a),e=d.length,f=0;f<b.b;f++){b.p[f]=k;for(var g=0;g<e;g++)if(b.j[f]==T(d[g])){b.p[f]=d[g];c=l;break}}return c}
V.prototype.O=function(b){if(!this.C&&this.b!=this.l){for(var a=S(b),c=Math.min(a.length,this.l-this.b),d=0;d<c;d++){var e=a[d];this.j[this.b]=T(e);this.s[this.b]=e.clientX;this.t[this.b]=e.clientY;this.b++}nb(this,b);if(this.b==this.l)for(d=0;d<this.l;d++)this.D[d]=this.F[d]=0;this.V(b)}};V.prototype.A=function(b){if(!this.C&&0<this.b&&nb(this,b)){this.n&&this.M(b);b=this.b;for(var a=0,c=0;c<b;c++)this.p[c]&&(this.j.splice(c-a,1),this.b--,this.n=p,a++)}};
V.prototype.reset=function(){this.b=0;this.C=this.n=p};function ob(b,a){var c=a||0,d=b.p[c];return d?d.clientX:b.d[b.j[c||0]]}function qb(b,a){var c=a||0,d=b.p[c];return d?d.clientY:b.i[b.j[c||0]]}function W(b,a,c){V.call(this,a,c,1);this.L=b;this.K=new kb}w(W,V);W.prototype.V=function(b){var a=this.K,c=this.s[0],d=this.t[0];b=b.timeStamp;a.h.length=a.f.length=0;a.h.push(c,b);a.f.push(d,b);a.v=c;a.I=d;this.v=this.s[0];this.I=this.t[0]};
W.prototype.U=function(b){a:{var a=this.L;if(a.e||!a.ma&&Math.abs(ob(a.m)-a.m.v)<=Math.abs(qb(a.m)-a.m.I))b=p;else{for(var c=0,d;d=a.S[c];++c)if(!d.Da(a,b)){b=p;break a}a.e++;a.X=b.target;for(c=0;d=a.S[c];++c)d.wa(a,b);a.q&&a.q(p);a.e++;Za(a.a,rb,a);a.e--;a.k=-1*a.a.parentNode.offsetWidth*a.g*a.r;a.J=a.k;sb(a);a.e--;b=!!a.X}}return b};
W.prototype.N=function(b){this.v=this.s[0];this.I=this.t[0];var a=this.K,c=ob(this),d=qb(this),e=b.timeStamp,f=a.h[a.h.length-2]-c,g=a.f[a.f.length-2]-d,h=a.h,n=a.da;n&&(f&&2<h.length&&0<n^0<f)&&h.splice(0,h.length-2);h=a.f;(n=a.ea)&&(g&&2<h.length&&0<n^0<g)&&h.splice(0,h.length-2);lb(a.h,e);lb(a.f,e);a.h.push(c,e);a.f.push(d,e);a.da=f;a.ea=g;a=this.L;a.e++;tb(a);sb(a);ub(a);a.e--;b.preventDefault()};
W.prototype.M=function(b){if(b){var a;a=this.K;var c=this.d[this.j[0]],d=this.i[this.j[0]],e=b.timeStamp;r(c)&&r(d)&&e?(lb(a.h,e),lb(a.f,e),c=a.h.length?(c-a.h[0])/(e-a.h[1]):0,d=a.f.length?(d-a.f[0])/(e-a.f[1]):0,c=mb(a,c),d=mb(a,d),a=new B(c,d)):a=k;this.aa=a||k;b.preventDefault()}a=this.L;a.e++;a.X=m;tb(a);ub(a);vb(a,100*a.k/a.a.offsetWidth,l);e=a.k*a.r;c=Math.round(-1*e/a.a.parentNode.offsetWidth);a.k=k;a.J=k;var d=(d=a.m.aa)?d.x*a.r:0,f=e+a.g*a.a.parentNode.offsetWidth;if(Math.abs(d)>a.Y){var g=
0>d;0!=f&&g!=0>f?c=a.g:c==a.g&&(c+=g?1:-1)}c=Math.max(0,Math.min(c,a.o.length-1));f=wb;g=c;e=Math.abs(e+c*a.a.parentNode.offsetWidth);d?(e=e!==k?e:a.a.parentNode.offsetWidth,d=!e?0:!a.g&&0<d||a.g==a.o.length-1&&0>d?a.w:Math.max(0,Math.min(a.w,e/(0.6259995851410399*Math.abs(d))))):d=a.w;f(a,g,d);a.e--;a=this.s[0];d=this.t[0];if(e=b)r(gb)||(e=Xa.exec(navigator.userAgent)||[],e.shift(),gb=Wa.apply(m,e)>=Wa(6)),e=gb;if(e)b.preventDefault();else{fb=k;U||(document.addEventListener("click",ib,l),b=jb,!Q&&
!R&&(b=db(b)),P(document,$a,b,l,l),U=[]);eb=da();for(b=0;b<U.length;b+=2)if(25>Math.abs(a-U[b])&&25>Math.abs(d-U[b+1])){U.splice(b,b+2);break}}};var xb=F?"ms":G?"Moz":ua?"O":"webkit",yb=(F?"-ms-":G?"-moz-":ua?"-o-":"-webkit-")+"transform",zb=xb+"Transform",Ab=xb+"Transition";function X(b,a,c){V.call(this,a,c,2);this.P=b}w(X,V);X.prototype.V=aa;X.prototype.U=function(b){return this.P.Aa(b)};X.prototype.N=function(b){this.P.za(b);b.preventDefault()};X.prototype.M=function(b){this.P.ya(b);b&&b.preventDefault()};
var Bb="WebKitCSSMatrix"in window&&"m11"in new WebKitCSSMatrix("");function Y(b){this.G=b;this.$=this.G.fa;this.d={};this.i={};this.c=[]}var Cb=[W,X];
Y.prototype.la=function(b){var a=b.touches||[b],c=a.length,d;for(d in this.d){for(var e=0;e<c;e++)if(d==T(a[e])){var f=l;break}f||Db(this,+d)}a=S(b);c=a.length;for(e=0;e<c;e++)d=T(a[e]),r(this.d[d])&&Db(this,+d);c=l;e=this.c.length;for(a=0;a<e;a++)if((d=this.c[a])&&d.b!=d.l){c=p;break}if(!c&&this.G.O(b)){c=S(b);d=c.length;for(a=0;a<d;a++){var f=c[a],g=T(f);this.d[g]=f.clientX;this.i[g]=f.clientY}for(a=0;a<e;a++)(d=this.c[a])&&d.O(b)}};
Y.prototype.ka=function(b){for(var a=l,c=this.c.length,d=0;d<c;d++){var e=this.c[d];if(e&&0<e.b){a=p;break}}if(!a){for(d=0;d<c;d++)if(e=this.c[d])if(a=e,e=b,!a.C&&a.b==a.l&&nb(a,e))if(a.n)a.N(e);else{for(var f=k,g=0;g<a.l;g++){var h=a.p[g];if(h){var n=a.j[g],y=a.i[n]-h.clientY;a.D[g]+=Math.abs(a.d[n]-h.clientX);a.F[g]+=Math.abs(y);f=f||2<a.D[g]||2<a.F[g]}}if(f){for(g=0;g<a.l;g++)a.s[g]=ob(a,g),a.t[g]=qb(a,g);a.n=a.U(e);a.n?a.N(e):a.reset()}}b=S(b);c=b.length;for(d=0;d<c;d++)a=b[d],e=T(a),r(this.d[e])&&
(this.d[e]=a.clientX,this.i[e]=a.clientY)}};Y.prototype.ja=function(b){for(var a=S(b),c=a.length,d,e=0;e<c;e++){var f=a[e],f=T(f);r(this.d[f])&&(this.G.A(b),d=l)}if(d){d=this.c.length;for(e=0;e<d;e++)(f=this.c[e])&&f.A(b);for(e=0;e<c;e++)f=a[e],f=T(f),r(this.d[f])&&(delete this.d[f],delete this.i[f])}};
function Db(b,a){b.G.A(m);for(var c=b.c.length,d=0;d<c;d++){var e=b.c[d];if(e){var f=e;if(!f.C&&0<f.b){for(var e=k,g=0;g<f.b;g++)if(f.j[g]==a){e=g;break}r(e)&&(f.n&&f.M(m),f.j.splice(e,1),f.b--,f.n=p)}}}delete b.d[a];delete b.i[a]}Y.prototype.enable=function(b,a){var c=v(this.ja,this),d=this.$,e=v(this.la,this),f=v(this.ka,this),g=c;!Q&&!R&&(e=db(e),f=db(f),g=db(g));var h=!!b;P(d,$a,e,h,a);P(d,ab,f,h,a);P(d,bb,g,h,a);P(d,cb,c,h,a)};
Y.prototype.reset=function(){for(var b in this.d)delete this.d[Number(b)],delete this.i[Number(b)];for(b=0;b<this.c.length;b++){var a=this.c[b];a&&a.reset()}};function Z(b,a,c){this.fa=this.a=b;this.o=a;this.g=c;this.S=[];this.qa=l;this.e=0}var rb="tableslider:start_slide_"+Ua++,Eb="tableslider:slide_move_"+Ua++,Fb="tableslider:card_changed_"+Ua++,Gb="tableslider:momentum_finished_"+Ua++;Z.prototype.w=500;Z.prototype.Y=0.5;Z.prototype.Z=0.5;Z.prototype.ma=p;
function Hb(b){b.T=new Y(b);var a;a:{a=b.a;var c=9==a.nodeType?a:a.ownerDocument||a.document;if(c.defaultView&&c.defaultView.getComputedStyle&&(a=c.defaultView.getComputedStyle(a,m))){a=a.direction||a.getPropertyValue("direction")||"";break a}a=""}b.r="rtl"==(a||(b.a.currentStyle?b.a.currentStyle.direction:m)||b.a.style&&b.a.style.direction)?-1:1;a=b.o.length;b.a.style.width=100*a+"%";a=100/a+"%";for(var c=0,d;d=b.o[c];c++)d.style.width=a;sb(b);b.T.enable(p);a=b.T;(c=a.c[0])?a=c:(c=new Cb[0](b,a.d,
a.i),a=a.c[0]=c);b.m=a}Z.prototype.O=function(){return l};function ub(b){b.e++;Za(b.a,Eb,b,{Ga:b.J,ra:b.k});b.e--}function tb(b){var a=ob(b.m)-b.m.v;(!b.g&&0<a*b.r||b.g==b.o.length-1&&0>a*b.r)&&(a*=b.Z);b.k=b.J+a}function wb(b,a,c){function d(b){d==this.q&&(this.q=k,this.e++,Za(this.a,Gb,this,{pa:f,sa:b}),this.e--)}b.q&&b.q(p);var e=b.g;b.g=a;sb(b,c);var f=Ib(b,e,a,c);b.q=d;window.setTimeout(v(d,b,l),c)}function Ib(b,a,c,d){b.e++;a={xa:a,ia:c,Ca:l,oa:l,Ha:d||0};Za(b.a,Fb,b,a);b.e--;return a}
function sb(b,a){b.a.style[Ab]=a?(yb||yb)+" "+a+"ms ease-out":"";r(b.k)?vb(b,b.k,p):vb(b,-100*b.g*b.r/b.o.length,l)}function vb(b,a,c){a+=c?"%":"px";a="number"==typeof a?a+"px":a||"0";b.a.style[zb]=Bb?"translate3d("+a+",0,0)":"translate("+a+",0)"}Z.prototype.A=aa;
function Jb(){var b=$,a=u("tour-wrapper")?document.getElementById("tour-wrapper"):"tour-wrapper",c=O("li",m,u("frame-indicator")?document.getElementById("frame-indicator"):"frame-indicator"),b=O("ul",b,a)[0],d=O("li",m,b),e=new Z(b,d,0);e.w=200;e.Y=0.01;Hb(e);P(b,Fb,function(b){b=b.ba.ia;var a;a=document;a=a.querySelectorAll&&a.querySelector?a.querySelectorAll(".selected"):a.getElementsByClassName?a.getElementsByClassName("selected"):O("*","selected",k);Ta(a[0]);Ta(c[b])});Ya(function(){e.Ba(a.offsetWidth)})}
var Kb=sa(),$="tablet";if(Kb.match("Android.*Chrome/[.0-9]* Mobile")||Kb.match(".*iPhone.*"))$="phone";else if(Kb.match("Android.*Chrome/[.0-9]* (?!Mobile)")||Kb.match(".*iPad.*"))$="tablet";$&&(Qa(document.documentElement,$),Jb());
})()